const videoUpload=document.getElementById("videoUpload"),referenceUpload=document.getElementById("referenceUpload"),video=document.getElementById("video"),overlay=document.getElementById("overlay"),ctxOverlay=overlay.getContext("2d"),modelStatus=document.getElementById("modelStatus"),sampleRate=document.getElementById("sampleRate"),confidenceThreshold=document.getElementById("confidenceThreshold"),keywordInput=document.getElementById("keywordInput"),analyzeBtn=document.getElementById("analyzeBtn"),downloadCsvBtn=document.getElementById("downloadCsvBtn"),downloadJsonBtn=document.getElementById("downloadJsonBtn"),statusEl=document.getElementById("status"),referenceList=document.getElementById("referenceList"),resultsEl=document.getElementById("results"),framesScannedEl=document.getElementById("framesScanned"),peopleDetectedEl=document.getElementById("peopleDetected"),shirtCapturesEl=document.getElementById("shirtCaptures"),textHitsEl=document.getElementById("textHits");let model=null,ocrWorker=null,currentVideoName="",results=[],references=[],totalPeople=0,totalTextHits=0;const workCanvas=document.createElement("canvas"),workCtx=workCanvas.getContext("2d"),labelOptions=["Unlabeled","Ohio State","NKU","UC","Miami","Nike","Adidas","Jordan","Champion","Under Armour","Other University","Other Brand","Unknown"];
async function init(){try{await tf.setBackend("webgl");await tf.ready();model=await cocoSsd.load();ocrWorker=await Tesseract.createWorker("eng");modelStatus.textContent="AI + OCR ready";modelStatus.classList.add("ready");statusEl.textContent="Ready. Upload a video and optional reference logos/images.";analyzeBtn.disabled=!video.src}catch(e){console.error(e);modelStatus.textContent="Load failed";statusEl.textContent="Model or OCR failed to load. Check your internet connection and browser console."}}
videoUpload.addEventListener("change",()=>{const f=videoUpload.files[0];if(!f)return;currentVideoName=f.name;const url=URL.createObjectURL(f);resetAnalysis();video.src=url;video.onloadedmetadata=()=>{resizeOverlay();analyzeBtn.disabled=!model||!ocrWorker;statusEl.textContent=`Loaded "${f.name}" (${Math.round(video.duration)} seconds).`}});
referenceUpload.addEventListener("change",async()=>{references=[];referenceList.innerHTML="";for(const f of [...referenceUpload.files]){const img=await loadImageFromFile(f),signature=getImageSignature(img);references.push({label:cleanReferenceLabel(f.name),fileName:f.name,signature})}renderReferenceList()});
window.addEventListener("resize",resizeOverlay);analyzeBtn.addEventListener("click",analyzeVideo);downloadCsvBtn.addEventListener("click",downloadCsv);downloadJsonBtn.addEventListener("click",downloadJson);
async function analyzeVideo(){if(!model||!ocrWorker||!video.duration)return;resetAnalysis(false);analyzeBtn.disabled=true;downloadCsvBtn.disabled=true;downloadJsonBtn.disabled=true;const interval=Number(sampleRate.value),minScore=Number(confidenceThreshold.value),duration=video.duration;workCanvas.width=video.videoWidth;workCanvas.height=video.videoHeight;let frameCount=0;for(let time=0;time<duration;time+=interval){await seekVideo(time);workCtx.drawImage(video,0,0,workCanvas.width,workCanvas.height);const predictions=await model.detect(workCanvas),people=predictions.filter(p=>p.class==="person"&&p.score>=minScore);totalPeople+=people.length;drawOverlay(people,workCanvas.width,workCanvas.height);for(const person of people)await captureAndAnalyzeShirtCandidate(person,time);frameCount++;updateStats(frameCount);statusEl.textContent=`Scanning... frame ${frameCount}, timestamp ${formatTime(time)}, people in frame: ${people.length}.`;await sleep(60)}statusEl.textContent=`Scan complete. Captured ${results.length} shirt/logo regions.`;analyzeBtn.disabled=false;downloadCsvBtn.disabled=results.length===0;downloadJsonBtn.disabled=results.length===0}
async function captureAndAnalyzeShirtCandidate(person,time){const [x,y,w,h]=person.bbox,cropX=clamp(x+w*.08,0,workCanvas.width),cropY=clamp(y+h*.22,0,workCanvas.height),cropW=clamp(w*.84,1,workCanvas.width-cropX),cropH=clamp(h*.45,1,workCanvas.height-cropY);if(cropW<45||cropH<45)return;const cropCanvas=document.createElement("canvas");cropCanvas.width=Math.round(cropW);cropCanvas.height=Math.round(cropH);const cropCtx=cropCanvas.getContext("2d");cropCtx.drawImage(workCanvas,cropX,cropY,cropW,cropH,0,0,cropCanvas.width,cropCanvas.height);const imageData=cropCanvas.toDataURL("image/jpeg",.82),ocrText=await readTextFromCanvas(cropCanvas),keywordHits=findKeywordHits(ocrText),referenceMatch=references.length?findBestReferenceMatch(cropCanvas):null;if(keywordHits.length>0)totalTextHits+=1;const predictedLabel=inferLabel(keywordHits,referenceMatch),row={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),videoName:currentVideoName,timestamp:formatTime(time),seconds:Number(time.toFixed(2)),predictedLabel,ocrText,keywordHits,referenceMatch,confidence:Math.round(person.score*100),manualLabel:"Unlabeled",note:"",bbox:{x:Math.round(x),y:Math.round(y),width:Math.round(w),height:Math.round(h)},crop:{x:Math.round(cropX),y:Math.round(cropY),width:Math.round(cropW),height:Math.round(cropH)},imageData};results.push(row);renderResult(row,results.length)}
async function readTextFromCanvas(canvas){try{const result=await ocrWorker.recognize(canvas);return result.data.text.replace(/\s+/g," ").trim()}catch(e){console.error("OCR failed",e);return""}}
function findKeywordHits(text){const normalizedText=normalizeText(text);if(!normalizedText)return[];return keywordInput.value.split(",").map(k=>k.trim()).filter(Boolean).filter(k=>normalizedText.includes(normalizeText(k)))}
function inferLabel(keywordHits,referenceMatch){if(keywordHits.length){const hit=keywordHits[0].toLowerCase();if(hit.includes("ohio")||hit.includes("buckeye")||hit==="osu")return"Possible Ohio State";if(hit.includes("nku")||hit.includes("northern kentucky"))return"Possible NKU";if(hit==="uc"||hit.includes("cincinnati"))return"Possible UC";if(hit.includes("miami"))return"Possible Miami";if(hit.includes("nike"))return"Possible Nike";if(hit.includes("adidas"))return"Possible Adidas";if(hit.includes("jordan"))return"Possible Jordan";if(hit.includes("champion"))return"Possible Champion";return`Possible ${keywordHits[0]}`}if(referenceMatch&&referenceMatch.score>=78)return`Reference match: ${referenceMatch.label}`;if(referenceMatch&&referenceMatch.score>=65)return`Weak reference match: ${referenceMatch.label}`;return"Unknown / needs review"}
function findBestReferenceMatch(canvas){const cropSignature=getImageSignature(canvas);let best=null;for(const ref of references){const score=compareSignatures(cropSignature,ref.signature);if(!best||score>best.score)best={label:ref.label,fileName:ref.fileName,score:Math.round(score)}}return best}
function getImageSignature(imageSource){const size=16,canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const ctx=canvas.getContext("2d");ctx.drawImage(imageSource,0,0,size,size);const data=ctx.getImageData(0,0,size,size).data,signature=[];for(let i=0;i<data.length;i+=4){const r=data[i]/255,g=data[i+1]/255,b=data[i+2]/255;signature.push(Number(((r+g+b)/3).toFixed(3)))}return signature}
function compareSignatures(a,b){const length=Math.min(a.length,b.length);let difference=0;for(let i=0;i<length;i++)difference+=Math.abs(a[i]-b[i]);return clamp((1-difference/length)*100,0,100)}
function renderResult(row,number){const card=document.createElement("article");card.className="result-card";card.dataset.resultId=row.id;const labelOptionsHtml=labelOptions.map(l=>`<option value="${escapeHtml(l)}">${escapeHtml(l)}</option>`).join(""),hitText=row.keywordHits.length?`<span class="hit">${row.keywordHits.join(", ")}</span>`:"None",referenceText=row.referenceMatch?`${escapeHtml(row.referenceMatch.label)} (${row.referenceMatch.score}%)`:"No reference images uploaded";card.innerHTML=`<img src="${row.imageData}" alt="Shirt or logo candidate ${number}" /><div class="result-body"><div class="result-top"><strong>Candidate ${number}</strong><span class="pill dark">${row.timestamp}</span></div><p class="result-meta"><strong>Prediction:</strong> ${escapeHtml(row.predictedLabel)}<br><strong>OCR hits:</strong> ${hitText}<br><strong>OCR text:</strong> ${escapeHtml(row.ocrText||"No readable text")}<br><strong>Reference match:</strong> ${referenceText}<br><strong>Person confidence:</strong> ${row.confidence}%</p><label class="manual-label">Manual label<select data-action="label">${labelOptionsHtml}</select></label><label class="manual-label">Notes<input data-action="note" type="text" placeholder="Example: red Ohio State sweatshirt..." /></label></div>`;card.querySelector('[data-action="label"]').addEventListener("change",e=>row.manualLabel=e.target.value);card.querySelector('[data-action="note"]').addEventListener("input",e=>row.note=e.target.value);resultsEl.appendChild(card)}
function drawOverlay(people,sourceW,sourceH){resizeOverlay();ctxOverlay.clearRect(0,0,overlay.width,overlay.height);const scaleX=overlay.width/sourceW,scaleY=overlay.height/sourceH;people.forEach(person=>{const[x,y,w,h]=person.bbox;ctxOverlay.lineWidth=3;ctxOverlay.strokeStyle="#facc15";ctxOverlay.strokeRect(x*scaleX,y*scaleY,w*scaleX,h*scaleY);const label=`person ${Math.round(person.score*100)}%`;ctxOverlay.font="14px Arial";const labelWidth=ctxOverlay.measureText(label).width+16;ctxOverlay.fillStyle="rgba(0,0,0,.74)";ctxOverlay.fillRect(x*scaleX,y*scaleY-30,labelWidth,26);ctxOverlay.fillStyle="#fff";ctxOverlay.fillText(label,x*scaleX+8,y*scaleY-12)})}
function renderReferenceList(){referenceList.innerHTML=references.length?references.map(ref=>`<span class="reference-chip">${escapeHtml(ref.label)}</span>`).join(""):""}
function downloadCsv(){const header=["videoName","timestamp","seconds","predictedLabel","manualLabel","ocrText","keywordHits","referenceLabel","referenceScore","personConfidence","note"],rows=results.map(row=>[row.videoName,row.timestamp,row.seconds,row.predictedLabel,row.manualLabel,row.ocrText,row.keywordHits.join("; "),row.referenceMatch?row.referenceMatch.label:"",row.referenceMatch?row.referenceMatch.score:"",`${row.confidence}%`,row.note]),csv=[header,...rows].map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");downloadBlob(csv,"logolens-v2-results.csv","text/csv")}
function downloadJson(){const safeResults=results.map(({imageData,...rest})=>rest),payload={project:"LogoLens AI",version:"V2 OCR + reference matching",generatedAt:new Date().toISOString(),note:"Image data excluded from JSON export to keep file size smaller.",references:references.map(ref=>({label:ref.label,fileName:ref.fileName})),results:safeResults};downloadBlob(JSON.stringify(payload,null,2),"logolens-v2-results.json","application/json")}
function downloadBlob(content,filename,mimeType){const blob=new Blob([content],{type:mimeType}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url)}
function loadImageFromFile(file){return new Promise(resolve=>{const image=new Image();image.onload=()=>resolve(image);image.src=URL.createObjectURL(file)})}
function cleanReferenceLabel(filename){return filename.replace(/\.[^/.]+$/," ").replace(/[-_]+/g," ").replace(/\s+/g," ").trim()}
function normalizeText(text){return String(text).toLowerCase().replace(/[^a-z0-9 ]/g," ").replace(/\s+/g," ").trim()}
function resizeOverlay(){overlay.width=video.clientWidth||1;overlay.height=video.clientHeight||1}
function seekVideo(time){return new Promise(resolve=>{video.currentTime=Math.min(time,video.duration||time);video.onseeked=()=>resolve()})}
function updateStats(frameCount){framesScannedEl.textContent=frameCount;peopleDetectedEl.textContent=totalPeople;shirtCapturesEl.textContent=results.length;textHitsEl.textContent=totalTextHits}
function resetAnalysis(clearOverlay=true){results=[];totalPeople=0;totalTextHits=0;resultsEl.innerHTML="";updateStats(0);downloadCsvBtn.disabled=true;downloadJsonBtn.disabled=true;if(clearOverlay)ctxOverlay.clearRect(0,0,overlay.width,overlay.height)}
function sleep(ms){return new Promise(resolve=>setTimeout(resolve,ms))}function clamp(value,min,max){return Math.min(Math.max(value,min),max)}function formatTime(seconds){const m=Math.floor(seconds/60),s=Math.floor(seconds%60);return`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}function escapeHtml(value){return String(value).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}init();
